Camera:
  fx: 426.372
  fy: 425.671
  cx: 435.525
  cy: 244.974

Algorithm:
  frame_step: 15
  cache_file: "cache.json"

Sequence1:
  image_dir: "/home/zah/ORB_SLAM3-master/landmarkslam/implement/data/test_pairs/pair_15_59/seq1/rgb"
  depth_dir: "/home/zah/ORB_SLAM3-master/landmarkslam/implement/data/test_pairs/pair_15_59/seq1/depth"
  trajectory_path: "/home/zah/ORB_SLAM3-master/landmarkslam/implement/data/test_pairs/pair_15_59/seq1/trajectory.txt"
  roi_path: "/home/zah/ORB_SLAM3-master/landmarkslam/implement/data/test_pairs/pair_15_59/seq1/rgb/corners.txt"

Sequence2:
  image_dir: "/home/zah/ORB_SLAM3-master/landmarkslam/implement/data/test_pairs/pair_15_59/seq2/rgb"
  trajectory_path: "/home/zah/ORB_SLAM3-master/landmarkslam/implement/data/test_pairs/pair_15_59/seq2/trajectory.txt"
